[server]
runOnSave = true
address = "127.0.0.1"

[browser]
gatherUsageStats = false

[theme]
backgroundColor = '#000000'
secondaryBackgroundColor = '#291f24'
primaryColor = '#ff0000'
textColor = '#ff7110'
font = 'sans serif'