[server]
runOnSave = true
address = "127.0.0.1"

[browser]
gatherUsageStats = false

[theme]
backgroundColor = '#021923'
secondaryBackgroundColor = '#034856'
primaryColor = '#7cffb9'
textColor = '#d4e6f3'
font = 'sans serif'