[server]
runOnSave = true
address = "127.0.0.1"

[client]
toolbarMode = "minimal"

[browser]
gatherUsageStats = false

[theme]
backgroundColor = '#161616'
secondaryBackgroundColor = '#3e4646'
primaryColor = '#2fda1b'
textColor = '#baffd2'
font = 'sans serif'